# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anomaly_detection.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61nomaly_detection.proto\x12\x13networkassistant.ml\"K\n\x0fMetricDataPoint\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\x12\x13\n\x0bmetric_name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\"\x97\x01\n\x17\x41nomalyDetectionRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x39\n\x0b\x64\x61ta_points\x18\x02 \x03(\x0b\x32$.networkassistant.ml.MetricDataPoint\x12\x17\n\x0fwindow_start_ms\x18\x03 \x01(\x03\x12\x15\n\rwindow_end_ms\x18\x04 \x01(\x03\"\x9b\x01\n\rAnomalyResult\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\x12\x13\n\x0bmetric_name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x0f\n\x07z_score\x18\x04 \x01(\x01\x12\x12\n\nis_anomaly\x18\x05 \x01(\x08\x12\x15\n\ranomaly_score\x18\x06 \x01(\x01\x12\x14\n\x0c\x61nomaly_type\x18\x07 \x01(\t\"\xa1\x01\n\x18\x41nomalyDetectionResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x35\n\tanomalies\x18\x02 \x03(\x0b\x32\".networkassistant.ml.AnomalyResult\x12 \n\x18overall_anomaly_detected\x18\x03 \x01(\x08\x12\x19\n\x11max_anomaly_score\x18\x04 \x01(\x01\x32\x89\x01\n\x17\x41nomalyDetectionService\x12n\n\x0f\x44\x65tectAnomalies\x12,.networkassistant.ml.AnomalyDetectionRequest\x1a-.networkassistant.ml.AnomalyDetectionResponseB,\n(com.example.networkanomalyassistant.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anomaly_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.example.networkanomalyassistant.grpcP\001'
  _globals['_METRICDATAPOINT']._serialized_start=48
  _globals['_METRICDATAPOINT']._serialized_end=123
  _globals['_ANOMALYDETECTIONREQUEST']._serialized_start=126
  _globals['_ANOMALYDETECTIONREQUEST']._serialized_end=277
  _globals['_ANOMALYRESULT']._serialized_start=280
  _globals['_ANOMALYRESULT']._serialized_end=435
  _globals['_ANOMALYDETECTIONRESPONSE']._serialized_start=438
  _globals['_ANOMALYDETECTIONRESPONSE']._serialized_end=599
  _globals['_ANOMALYDETECTIONSERVICE']._serialized_start=602
  _globals['_ANOMALYDETECTIONSERVICE']._serialized_end=739
# @@protoc_insertion_point(module_scope)
