# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: causal_inference.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63\x61usal_inference.proto\x12\x13networkassistant.ml\"D\n\nCausalNode\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\x15\n\ranomaly_score\x18\x03 \x01(\x01\"[\n\nCausalEdge\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x11\n\ttarget_id\x18\x02 \x01(\t\x12\x17\n\x0f\x64\x65pendency_type\x18\x03 \x01(\t\x12\x0e\n\x06weight\x18\x04 \x01(\x01\"\xae\x01\n\x12\x43\x61usalGraphRequest\x12.\n\x05nodes\x18\x01 \x03(\x0b\x32\x1f.networkassistant.ml.CausalNode\x12.\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x1f.networkassistant.ml.CausalEdge\x12\x1c\n\x14time_window_start_ms\x18\x03 \x01(\x03\x12\x1a\n\x12time_window_end_ms\x18\x04 \x01(\x03\"\x86\x01\n\x13RootCauseHypothesis\x12\x1a\n\x12root_cause_node_id\x18\x01 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x02 \x01(\x01\x12$\n\x1csupporting_evidence_node_ids\x18\x03 \x03(\t\x12\x13\n\x0b\x65xplanation\x18\x04 \x01(\t\"v\n\x17\x43\x61usalInferenceResponse\x12<\n\nhypotheses\x18\x01 \x03(\x0b\x32(.networkassistant.ml.RootCauseHypothesis\x12\x1d\n\x15primary_root_cause_id\x18\x02 \x01(\t2\x81\x01\n\x16\x43\x61usalInferenceService\x12g\n\x0eInferRootCause\x12\'.networkassistant.ml.CausalGraphRequest\x1a,.networkassistant.ml.CausalInferenceResponseB,\n(com.example.networkanomalyassistant.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'causal_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.example.networkanomalyassistant.grpcP\001'
  _globals['_CAUSALNODE']._serialized_start=47
  _globals['_CAUSALNODE']._serialized_end=115
  _globals['_CAUSALEDGE']._serialized_start=117
  _globals['_CAUSALEDGE']._serialized_end=208
  _globals['_CAUSALGRAPHREQUEST']._serialized_start=211
  _globals['_CAUSALGRAPHREQUEST']._serialized_end=385
  _globals['_ROOTCAUSEHYPOTHESIS']._serialized_start=388
  _globals['_ROOTCAUSEHYPOTHESIS']._serialized_end=522
  _globals['_CAUSALINFERENCERESPONSE']._serialized_start=524
  _globals['_CAUSALINFERENCERESPONSE']._serialized_end=642
  _globals['_CAUSALINFERENCESERVICE']._serialized_start=645
  _globals['_CAUSALINFERENCESERVICE']._serialized_end=774
# @@protoc_insertion_point(module_scope)
